# Generated by Django 5.1.4 on 2024-12-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_created_at_category_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
